### ISSUE TITLE
Compiling test/dump.f results in error message "test/dump.f:14: undefined word 'invis'" 

### ISSUE THREAD

**Issue by dbolli** [petrihakkinen/ace-forth#1]
Using either

```
./compile.lua -o test/dump.tap -l test/dump.lst --filename dump --main dump --optimize test/dump.f
```

or

`./compile.lua -o test/dump.tap -l test/dump.lst --filename dump --main dump --mcode --optimize test/dump.f`

the compile fails with 

`test/dump.f:14: undefined word 'invis'
`

error message

I'm using

```
lua -v
Lua 5.4.4  Copyright (C) 1994-2022 Lua.org, PUC-Rio

```
installed on macOS 12.2.1 via brew

Other test demo forth files compile successfully e.g. starfield.f, memtest.f and mcode.f (which contains invis) and I can see INVIS defined in the compile.lua script

**Comment by petrihakkinen** [comment]
Sorry for the long delay! The test code does not compile because the word INVIS is undefined at compile time (it's a word defined in Jupiter Ace's ROM). Anyway, I've cleaned up test/dump.f so that it compiles now without errors.
